log_level: "info"
log_path: "/var/log/electermsync.log"
jwt_secret: "mysectet2025"
jwt_users: "root"
file_store_path: "/root/elecdata"
listen: "0.0.0.0:7837"
acl_whitelist:
  - "127.0.0.1"
  - "192.168.1.*"
  - "192.168.99.0/24"
